config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resources :users do
    resources :wards, only: [:create, :destroy, :update]
    resources :tutor_details
  end

  resources :sessions, only: [:create, :destroy]
  resources :bookings, only: [:create, :destroy]

  get "tutor_details/search", to: "tutor_details#search"
  get "/generate_ward_page", to: "wards#generate_page"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :tutor_detail
  belongs_to :ward
  has_one :subject
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :tutor_detail

end

app/models/specialization.rb
class Specialization < ActiveRecord::Base
  belongs_to :tutor_detail
  has_one :subject
  

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :tutorial_subject
  has_one :specialization
end

app/models/tutor_detail.rb
class TutorDetail < ActiveRecord::Base
  has_many :specializations
  belongs_to :user
 

end

app/models/tutorial_subject.rb
class TutorialSubject < ActiveRecord::Base
  belongs_to :ward
  has_one :subject
end

app/models/tutorialsubject.rb
class Tutorialsubject < ActiveRecord::Base
  belongs_to :ward
  has_one :subject
  

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :wards
  has_one :tutor_detail


  validates :first_name, :last_name, :address, :phone_number, :email,
            :postal_code, :city, :province, :account_type, presence: true

end

app/models/ward.rb
class Ward < ActiveRecord::Base
  belongs_to :user
  has_many :tutorial_subjects
  has_many :bookings

  validates :first_name, :grade_school_level, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def subject_list
    @subject =  Subject.all()
  end

  def allTutors
    @tutor=TutorDetail.all()

  end

  helper_method :subject_list, :allTutors

  def bookings_list
    @bookings = Booking.all()
  end

  helper_method :bookings_list
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    booking = Booking.new(booking_params)
    if booking.save
      redirect_to '/users'
    else
      redirect_to :back
    end
  end

  def destroy
  end

  private

  def booking_params
    params.permit(:tutor_detail_id, :ward_id, :subject_id, :booking_start, :booking_end)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
    end
    redirect_to '/users'
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    render 'index'
  end

end

app/controllers/tutor_details_controller.rb
class TutorDetailsController < ApplicationController

  def index
    if current_user.blank?
      render "login"
    else
      render "tutor_detailed_homepage.html.erb"
    end
  end

  def show
    render 'show'
  end

  def create
    tutor_detail = TutorDetail.new(tutor_detail_params)
    if tutor_detail.save
      tutor_detail.specializations.create(specilization_params)
      redirect_to user_tutor_details_path, notice: "your information was submitted successfully!"
    else
       redirect_to :back
    end

  end

  def search
    location = params[:location]
    ward_grade = params[:grade]
    subject = params[:subject]
    tutor_user_ids = User.where(:account_type => 'tutor').where(["address LIKE ?", "%#{params[:location]}%"]).ids
    @tutor_result = TutorDetail.where(:user_id => tutor_user_ids)
    render 'search.html.erb'
  end


 private

 def tutor_detail_params
       params.permit(:user_id, :bio, :image)
  end

  def specilization_params
       params.permit(:years_of_experience, :qualification1, :qualification2, :subject_id )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  def has_wards?
    if @current_user.wards.blank?
      return false
    else
      return true
    end
  end
  helper_method :has_wards?

  def index
    if current_user.blank?
      render "login"
    else
      redirect_to "/users/#{current_user.id}"
    end
  end

  def show
    if current_user.account_type == "parent"
      render "parent_home"
    elsif current_user.account_type == "tutor"
      render "tutor_detailed_homepage.html.erb"
    end
  end

  def new
    account_type = params[:account_type]
    render "signup", :locals => {:account_type => account_type}
  end

  def edit

  end

  def update
  end

  def destroy
  end

  def search

  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
        if current_user.account_type == "tutor"
          render "tutor-information-form.html.erb"
        else 
           redirect_to '/users'
        end 
    else
      account_type = params[:account_type]
      render "signup", :locals => {:account_type => account_type}
    end
  end

  def search
    render "tutor_search"
  end

  private

  def user_params
    params.permit(:first_name, :last_name, :phone_number, :address,
      :city, :province, :postal_code, :email, :account_type,
      :password, :password_confirmation)
  end

end

app/controllers/wards_controller.rb
class WardsController < ApplicationController

  def create
    ward = Ward.new(ward_params)
    if ward.save
      tutorial_params[:subject_ids].each do |id|
      subject_id = {"subject_id" => id}
      ward.tutorial_subjects.create(subject_id)
    end
      redirect_to :back
    else
      # show errors
    end
  end

  def generate_page
    @selected = Ward.find(params[:ward_id])
    respond_to do |format|
      format.js
    end
  end

  private

  def ward_params
    params.permit(:first_name, :grade_school_level, :user_id)
  end

  def tutorial_params
    params.permit(:subject_ids => [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def generate_subjects_list
    
  end

end

app/views/calendar_templates/_tutor_booking.html.erb
<script type="text/template" id="tutor_booking_clndr_template">

  <!-- Calendar header and controls -->
  <div class="clndr-controls">
    <div class="clndr-previous-button">&lt;</div>
    <div class="clndr-next-button">&gt;</div>
    <div class="current-month"><%%= month %> <%%= year %></div>
  </div>

  <!-- Calendar days grid -->
  <div class="clndr-grid">
    <div class="days-of-the-week clearfix">
      <%% _.each(daysOfTheWeek, function(day) { %>
        <div class="header-day"><%%= day %></div>
      <%% }); %>
    </div>
    <div class="days">
      <%% _.each(days, function(day) { %>
        <div class="<%%= day.classes %>" id="<%%= day.id %>"><span class="day-number"><%%= day.day %></span></div>
      <%% }); %>
    </div>
  </div>

</script>

app/views/calendar_templates/_ward_schedule.html.erb
<script type="text/template" id="ward_schedule_clndr_template">

  <!-- Calendar header and controls -->
  <div class="clndr-controls">
    <div class="clndr-previous-button">&lt;</div>
    <div class="clndr-next-button">&gt;</div>
    <div class="current-month"><%%= month %> <%%= year %></div>
  </div>

  <!-- Calendar days grid -->
  <div class="clndr-grid">
    <div class="days-of-the-week clearfix">
      <%% _.each(daysOfTheWeek, function(day) { %>
        <div class="header-day"><%%= day %></div>
      <%% }); %>
    </div>
    <div class="days">
      <%% _.each(days, function(day) { %>
        <div class="<%%= day.classes %>" id="<%%= day.id %>"><span class="day-number"><%%= day.day %></span></div>
      <%% }); %>
    </div>
  </div>

  <!-- Calendar events -->
  <div class="event-listing">
    <div class='event-listing-title'>Upcoming Tutoring Sessions</div>
    <%% _.each(eventsThisMonth, function(event) { %>
      <div class='event-item'>
        <div class='event-item-name'><%%= event.title %></div>
        <div class="event-item-date"><%%= event.start_time %></div>
      </div>
    <%% }); %>
  </div>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edututor</title>
  <%= stylesheet_link_tag    'application', 'users', 'multiselect', 'calendar', 'static_pages', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'tutors', 'parents', 'static_pages', 'multiselect', 'calendar', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="page-container">
  <% if params[:controller] == "static_pages" %>
  <!-- Static_pages Navbar -->
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Edu-tutor</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="#learn">Learn</a></li>
          <li><a href="#teach">Teach</a></li>
          <li><a href="#about">About Us</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/users">Login</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <% else %>
  <!-- Navbar -->
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="/users">Edu-tutor</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="navbar-account">
        <ul class="nav navbar-nav navbar-right">
          <!-- Login link if not signed in-->
          <% if current_user.blank? %>
            <li><a href="/users">Login</a></li>
          <% else %>
          <!-- Profile link if a user is signed in -->
            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <%= current_user.first_name %> <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu">
                <li><a href="#">Edit Profile</a></li>
                <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
              </ul>
            </div>
          <% end %>
        </ul>
        <div class="nav navbar-note navbar-right">
        </div>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <% end %>

  <%= yield %>

  <div class="push"></div>
</div>
<div class="footer">
  <div class="copyright">
    <h5>&copy Copyright Edu-tutor 2016</h5>
  </div>
</div>
</body>
</html>

app/views/non_user/index.html.erb
<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Edu-tutor</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Learn</a></li>
        <li><a href="#">Teach</a></li>
        <li><a href="#">About Us</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- Slider -->
<div class='container non_user_slider'>
  <div class="slider_container">
    <h1>Edu-tutor</h1>
    <p>We all want to give our kids the best education.</p>
    <p>Edu-tutor makes it easy for you to find the best home tutors for your kids.</p>
    <button class="pull-right" type="button" name="signup">Sign up</button>
  </div>
</div>

<!-- Teach & Learn-->
<div class="container">
  <div class="teach col-md-6">
    <h1>Teach</h1>
    <p>We always welcome teachers who are passionate
about their subjects and want to make a difference in
the lives students to sign-up on our site</p>
    <button class="pull-right" type="button" name="tutor-signin">Tutor Sign up</button>
  </div>
  <div class="learn col-md-6">
    <h1>Learn</h1>
    <p>We want all Parents or Guardians who want to find best home tutors
for their wards or Kids on any Subject to sign-up</p>
    <button class="pull-right" type="button" name="parent-signin">Parent Sign up</button>
  </div>
</div>

<!-- Reviews -->
<div class="container">
  <div class="reviews">
    <div class="review col-md-5">
      <h3>Edu-tutor helped my child go from struggling in math to being top of his class!</h3>
      <h4>Scott McPhee</h4>
    </div>
    <div class="review col-md-5">
      <h3>I love using Edututor to help find tutors. It makes the whole proccess so much faster and easier.</h3>
      <h4>John Smith</h4>
    </div>
  </div>
</div>

app/views/parents/login.html.erb
<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Edu-tutor</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="login_parents">Login as Parent</a></li>
            <li><a href="login_tutors">Login as Tutor</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <div class="login col-md-4">
    <h1>Login As Parent</h1>
    <form class="login_form" action="/login_parents" method="get">
      <%= render "shared/login_form" %>
    </form>
  </div>
</div>

app/views/shared/_login_form.html.erb
<div class="form-div">
  <input type="text" name="email">
</div>
<div class="form-div">
  <input type="password" name="password">
</div>
<div class="form-div pull-right">
  <input type="submit" name="submit" value="Submit">
</div>

app/views/shared/_signup_form.html.erb
<form class="signup_form" action="/users" method="post">
  <div class="form-group">
    <label for="first_name">First name:</label>
    <input type="text" name="first_name">
  </div>
  <div class="form-group">
    <label for="last_name">Last name:</label>
    <input type="text" name="last_name">
  </div>
  <div class="form-group">
    <label for="phone">Phone:</label>
    <input type="tel" name="phone_number">
  </div>
  <div class="form-group">
    <label for="address">Address:</label>
    <input type="text" name="address">
  </div>
  <div class="form-group">
    <label for="city">City:</label>
    <input type="text" name="city">
    <label for="province">Province:</label>
    <input type="text" name="province">
    <label for="postal">Postal code:</label>
    <input type="text" name="postal_code">
  </div>
  <div class="form-group">
    <label for="email">Email:</label>
    <input type="email" name="email">
  </div>
  <div class="form-group">
    <label for="password">Password:</label>
    <input type="password" name="password">
    <label for="password_confirm">Confirm Password:</label>
    <input type="password" name="password_confirmation">
  </div>
  <div class="form-group pull-right">
    <input type="submit" name="submit" value="Submit">
  </div>
</form>

app/views/shared/_tutor_detail_specialization.html.erb
<div class="experience">
  <table>
    <tbody>
      <tr>
        <td>Subject:</td>
        <% subject_id = specialization.subject_id %>
        <td><%= subject_list.find(subject_id).subject_name %></td>
        <td> Experience(yrs): </td>
        <td> <%= specialization.years_of_experience %> </td>
        <td> Qualification: </td>
        <td> <%= specialization.qualification1 %>  </td>
        <td> Qualification: </td>
        <td> <%= specialization.qualification2 %> </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/shared/_tutor_search_result.html.erb
<a href="<%= url_for(user_tutor_detail_path(:user_id => current_user.id, :id => tutor.id) ) %>">

<div class="tutor_search_result">
  <div class="tutor_image">
    <img src="http://lorempixel.com/120/120/" alt="pew pew">
  </div>
  <div class="tutor_right">
    <div class="tutor_search_header">
      <% full_name = tutor.user.first_name + " " + tutor.user.last_name %>
      <h3><%= full_name %></h3>
      <h4>Rating:
      <% if tutor.average_review != nil %>
        <% rating = tutor.average_review %>
      <% else %>
        <% rating = 5 %>
      <% end %>
      <% for i in 1..rating %>
        ★
      <% end %>
      </h4>
    </div>
    <div class="tutor_search_body">
      <p>Subjects:
      <% tutor.specializations.each do |specialization| %>
        <% subject_id = specialization.subject_id %>
        <% if tutor.specializations.last() == specialization %>
          <%= subject_list.find(subject_id).subject_name %>
        <% else %>
          <%= subject_list.find(subject_id).subject_name + ", " %>
        <% end %>
      <% end %>
      </p>
      <p><%= tutor.user.address %>, <%= tutor.user.city %></p>
    </div>
  </div>
</div>

</a>

app/views/shared/_ward_subjects.html.erb
<h3>Subjects</h3>
<ul>
  <% ward.tutorial_subjects.each do |subject| %>
    <% id = subject.subject_id %>
    <% subject_list.each do |subject| %>
      <% if subject.id == id %>
        <li><%= subject.subject_name %></li>
      <% end %>
    <% end %>
  <% end %>
</ul>

app/views/shared/_ward_time_form.html.erb
<% days = ['mon','tue','wed','thu','fri','sat','sun'] %>
<% days.each do |day| %>
<tr class="hideAll element<%= day %>">
  <td class="showAtStart">
    <li>
      <input type="checkbox" id="<%= day %>"/>
      <label for="<%= day %>"><%= day.upcase %></label>
    </li>
  </td>
  <td>
    <p>Start time</p>
  </td>
  <td>
    <p> <input type="time" name="start_time"> </p>
  </td>
  <td>
    <p> End Time </p>
  </td>
  <td>
    <p> <input type="time" name="end_time"> </p>
  </td>
  <td>
    <p> Frequency </p>
  </td>
  <td>
    <p>
    <select name="Frequency">
      <option value=""> </option>
      <option value="once">once</option>
      <option value="weekly">weekly</option>
      <option value="bi-weekly"> bi-weekly</option>
      <option value="once monthly">once monthly</option>
    </select>
    </p>
  </td>
</tr>
<% end %>

app/views/users/parent_home.html.erb
<!-- Navigation header -->
<div class="container">
  <div class="wards_header">
    <!-- display dropdown with entries for each ward -->
    <!-- else display add new ward button and skip rendering wards info -->
    <% if has_wards? %>
    <div class="dropdown">
      <button type="button" id="ward_name" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <%= current_user.wards.first.first_name %>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenu">
        <% current_user.wards.each do |ward| %>
          <li><%= link_to ward.first_name, generate_ward_page_path(:js, :ward_id => ward.id), remote: true %></li>
        <% end %>
        <li><a data-toggle="modal" data-target="#newWardForm" style="cursor: pointer;">Add New Ward <span class="glyphicon glyphicon-plus"></span></a></li>
      </ul>
    </div>
    <% else %>
    <div class="dropdown">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newWardForm">Add New Ward
        <span class="glyphicon glyphicon-plus"></span></button>
    </div>
    <% end %>
    <div class="search_tutors pull-right">
      <a href="<%= url_for(controller: 'tutor_details', action: 'search') %>"><button class="btn btn-primary pull-right" type="button" name="tutor_search">Search Tutors</button></a>
    </div>
  </div>
</div>

<!-- Ward page render start -->
  <% if !current_user.wards.blank? %>

    <!-- Ward Schedule -->
    <div class="container">
      <% if current_user.wards.first.bookings.blank? %>
        <div id="ward_schedule_clndr"></div>
      <% else %>
        <div id="ward_schedule_clndr_events"></div>
      <% end %>
      <%= render :partial => './calendar_templates/ward_schedule' %>
    </div>

    <!-- Ward subjects -->
    <div id="ward_subjects" class="container">
      <%= render :partial => './shared/ward_subjects', locals: {ward: current_user.wards.first} %>
    </div>

    <!-- Reccomended Tutors -->
    <div class="recomended-tutors container">
      <h3>Recommended Tutors</h3>
      <%= render :partial => './shared/tutor_search_result', locals: {tutor: allTutors.first} %>
    </div>

  <% else %>

    <div class="container">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h4>Add a Ward</h4>
        </div>
        <div class="panel-body">
          <p>Add a ward to begin booking tutoring sessions.</p>
        </div>
      </div>
    </div>

  <% end %>

<!-- Ward page render stop -->

<!-- Add new ward modal -->
<div class="modal fade" id="newWardForm" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Ward</h4>
      </div>
      <div class="modal-body">
        <div id="addNewWardForm">
          <form id="newWardUser" action="/users/<%= current_user.id %>/wards" method="post">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <label for="first_name">First Name: </label>
            <input type="text" name="first_name">
            <label for="grade_school_level">Grade: </label>
            <select form="newWardUser" name="grade_school_level">
              <option value=""> </option>
              <% for i in 1..12 %>
                <option value="Grade <%= i %>">Grade <%= i %></option>
              <% end %>
            </select><br>
            <label for="subject_ids[]">Subject: </label>
            <select multiple class="multiple_select" form="newWardUser" name="subject_ids[]">
              <% subject_list.each do |subject| %>
                <% name = subject.subject_name %>
                <option value="<%= subject.id %>"><%= name %></option>
              <% end %>
            </select>
          </form>
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal">Close</button>
        <button class="btn btn-primary" id="addWardButton">Save</button>
      </div>
    </div>
  </div>
</div>

app/views/users/tutor_home.html.erb
<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Edu-tutor</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-auth">
      <ul class="nav navbar-nav navbar-right">
        <!-- Login link if not signed in-->
        <% if current_user.blank? %>
          <li><a href="/users">Login</a></li>
        <% else %>
        <!-- Logout link if a user is signed in -->
          <li>
            <%= link_to "Logout", session_path(current_user.id), method: :delete %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- Displaying the overall page view  -->
<div class="profile">
  <!-- Displaying the profile picture and Bio -->
  <div class="container">
    <div class="bio col-md-6">
      <%= image_tag "tutor.jpg" %>
      <h4> </h4>
    </div>
    <div class="bio col-md-6">
      <h4>Name: Stanley Brown</h4>
      <h5> Professional Bio: </h5>
      <p> A dedicated tutor with over 10 years
      experience teaching Maths and Computer science to pupils from
      Grade 6 to Grade 10.
      </p>
    </div>
  </div>


  <!-- Displaying Experience and Specilazation-->
  <div class="container">
    <div class="experience col-md-12">
      <h4>Specialization</h4>
      <table>
        <tbody>
          <tr>
            <td> Subject: </td>
            <td> Maths</td>
            <td> Experience(yrs): </td>
            <td> 3 </td>
            <td> Qualification1: </td>
            <td> BSc. Mathematics </td>
            <td> Qualification2: </td>
            <td> MSc. Mathematics</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="experience col-md-12">
      <table>
        <tbody>
          <tr>
            <td> Subject: </td>
            <td> English </td>
            <td> Experience(yrs): </td>
            <td> </td>
            <td> Qualification1: </td>
            <td> </td>
            <td> Qualification2: </td>
            <td> </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="experience col-md-12">
      <table>
        <tbody>
          <tr>
            <td> Subject: </td>
            <td>Computer science </td>
            <td> Experience(yrs): </td>
            <td> 10 </td>
            <td> Qualification1: </td>
            <td> </td>
            <td> Qualification2: </td>
            <td> </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <!-- parentt Reviews of tutors  -->
  <br>
  <br>
  <div class="container">
    <div> <h4> <li>Parents Reviews </li> </h4> </div>
      <div class="reviews_tutor">
        <div class="review col-md-6">
          <p>My sons performance increased dramatically after he began his lessons with Mr Stanley!</p>
          <h5>Scott, 25th of January, 2016 </h5>
          <hr>
        </div>
      </div>
    </div>
  <br>
  <div class="container">
    <div class="reviews_tutor">
      <div class="review col-md-6">
        <p>not only did my daughters English grade score increase, her attutide towards her studies also improved
        when stanley started home Tutoring with her</p>
        <h5>IDD ...  25th of March, 2015 </h5>
        <hr>
      </div>
    </div>
  </div>
</div>